version: '2'
services:
    review-postgresql:
        image: postgres:9.6.5
        # volumes:
        #     - ~/volumes/jhipster/review/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=review
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
